# GitHub Pages Configuration for D&D Voice Adventure
title: "D&D Voice Adventure"
description: "A comprehensive tabletop RPG companion with voice integration, inspired by Baldur's Gate 3 and Gloomhaven."
baseurl: ""
url: "https://taylor834-sketch.github.io"

# Repository information
repository: "taylor834-sketch/DND-Game"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - node_modules/
  - package.json
  - package-lock.json
  - .gitignore
  - .git/

# Include files
include:
  - _headers
  - _redirects

# Build settings
markdown: kramdown
highlighter: rouge
incremental: false

# SEO and metadata
author: "D&D Voice Adventure Team"
twitter:
  username: taylor834-sketch
  card: summary_large_image

social:
  name: D&D Voice Adventure
  links:
    - https://github.com/taylor834-sketch/DND-Game

# Collections (for future expansion)
collections_dir: collections

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: D&D Voice Adventure Team